return {}
-- return {
--   'folke/flash.nvim',
--   event = 'VeryLazy',
--   ---@type Flash.Config
--   opts = {},
--   -- stylua: ignore
--   keys = {
--     { "<CR>", mode = { "n", "x", "o" }, function() require("flash").jump() end, desc = "Flash" },
--     { "S", mode = { "n", "o" }, function() require("flash").treesitter() end, desc = "Flash Treesitter" },
--   },
-- }
