return {}
-- return {
--   'folke/noice.nvim',
--   event = 'VeryLazy',
--   dependencies = {
--     'MunifTanjim/nui.nvim',
--     'rcarriga/nvim-notify',
--   },
--   config = function()
--     local border_style = {
--       top_left = '╭',
--       top = '─',
--       top_right = '╮',
--       left = '│',
--       right = '│',
--       bottom_left = '╰',
--       bottom = '─',
--       bottom_right = '╯',
--     }
--
--     require('noice').setup {
--       lsp = {
--         override = {
--           ['vim.lsp.util.convert_input_to_markdown_lines'] = true,
--           ['vim.lsp.util.stylize_markdown'] = true,
--           ['cmp.entry.get_documentation'] = true,
--         },
--         -- Disable hover handling in noice
--         hover = {
--           enabled = false,
--         },
--         signature = {
--           enabled = true,
--           auto_open = {
--             enabled = true,
--             trigger = true,
--           },
--           opts = { border = border_style },
--         },
--         -- Add message handling for other LSP features
--         message = {
--           enabled = true,
--           view = 'notify',
--           opts = {},
--         },
--       },
--       presets = {
--         bottom_search = true,
--         command_palette = true,
--         long_message_to_split = true,
--         inc_rename = false,
--         lsp_doc_border = true,
--       },
--       views = {
--         cmdline_popup = {
--           position = {
--             row = '50%',
--             col = '50%',
--           },
--           size = {
--             width = 60,
--             height = 'auto',
--           },
--           border = { style = border_style },
--         },
--         popupmenu = {
--           border = { style = border_style },
--         },
--       },
--     }
--   end,
-- }
